version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai-email-app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    depends_on:
      - mongo
      - redis

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      args:   
        - REACT_APP_STRIPE_PUBLISHABLE_KEY=${REACT_APP_STRIPE_PUBLISHABLE_KEY}
        - REACT_APP_STRIPE_PRO_PRICE_ID=${REACT_APP_STRIPE_PRO_PRICE_ID}
    ports:
      - "3000:80"
    depends_on:
      - backend

  # MongoDB Database Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Redis Service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
